### ISSUE TITLE
Mixing warnings with errors

### ISSUE THREAD

**Issue by petr001** [gmullerb/eslint-plugin-regex#15]
At the moment only "error" or "warn" can be added to (all) "regex/invalid" patterns. Would be great to be able to specify patterns with error and patterns with warning.

**Comment by gmullerb** [comment]
**Thanks for proposing improvements!!** :sparkles::raised_hands: 
**It's a Great Idea!!** :+1: 
I will work on it as soon as I have a time.
Thanks!!!
