### ISSUE TITLE
Feature suggestion: Add the posibility to set custom RegEx flag

### ISSUE THREAD

**Issue by hccr** [gmullerb/eslint-plugin-regex#19]
The plugin always sets the RegEx flag to `gm`. It would be great to have the possibility to pass a custom regex flag as a parameter.
E.g., I needed to check a word case insensitive in my case, and I wrote three rules for that, but with a custom RegEx flag, it would be just one setting `gim` flags.

![Screen Shot 2022-05-18 at 17 38 51](https://user-images.githubusercontent.com/4325562/169554777-7de2dbd5-c38c-4524-b7f4-81468287f777.png)

**Comment by gmullerb** [comment]
**Thanks So Much for bringing this up!** :raised_hands:  :+1: 
As soon as possible, I will implement a feasible solution that allows to keep `gm` and add any additional required flag to the Regex.
