### ISSUE TITLE
Custom message

### ISSUE THREAD

**Issue by OliverFlint** [gmullerb/eslint-plugin-regex#2]
Hi, This is great! Only a few months ago I was looking if someone had done this. Couldn't find one and didn't have the time to code one myself. Any chance of adding the ability to provide a custom message? "Invalid regular expression" is a bit misleading.

Thanks anyway!

**Comment by gmullerb** [comment]
Absolutely, I had this in mind for the next version, but have had not time, and with the time the task got far away from the beginning of some trello list.
**Happy that you found it useful!** 
**Thanks!** 
I'll be looking for a time this weekend to do an upgrade!
