### ISSUE TITLE
Bump eslint?

### ISSUE THREAD

**Issue by epiqueras** [gmullerb/eslint-plugin-regex#4]
Hi, thanks for this useful plugin. I'm surprised there isn't a core rule for this.

Can we bump the `eslint` version required as a peer dependency?

I am using `"eslint": "^7.5.0"` and everything works fine, but `npm` warns about the mismatch.

**Comment by gmullerb** [comment]
**Happy that you found this package useful!!**
and **Thanks for bring this up!!** :+1:
